GET {{Api_HostAddress}}/api/activities
Accept: application/json

###

GET {{Api_HostAddress}}/api/activities/bcff89dc-1507-47e5-8ef8-02731ec12a8a
Accept: application/json

###

POST {{Api_HostAddress}}/api/activities
Content-Type: application/json
{
  "Title": "test title 2222222222",
  "Description": "test description xxx",
  "Category": "test category xxx",
  "City": "city xxx",
  "Venue": "venue xxx",
  "Latitude": 80,
  "Longitude": 100,
  "Date": "2026-04-30T15:34:32.2773742"
}

###

PUT {{Api_HostAddress}}/api/activities/12de06d9-cda4-443a-abf3-6c65103c87d3
Content-Type: application/json
{
  "Id": "12de06d9-cda4-443a-abf3-6c65103c87d3",
  "Title": "test title 1111 updated updated updated",
  "Description": "test description 111 updated",
  "Category": "test category 111 updated",
  "City": "city 111 updated",
  "Venue": "venue 111 updated",
  "Latitude": 80,
  "Longitude": 100,
  "Date": "2026-04-30T15:34:32.2773742"
}

### 

POST {{Api_HostAddress}}/api/activities/ff5c065a-1fbe-424a-92b4-d73d84e94fa3/attend
Content-Type: application/json

### 

POST {{Api_HostAddress}}/api/login
Content-Type: application/json
{
  "email": "bob@test.com",
  "password": "Pa$$w0rd"
}

### Login and receving Cookie

POST {{Api_HostAddress}}/api/login?useCookies=true
Content-Type: application/json
{
  "email": "bob@test.com",
  "password": "Pa$$w0rd"
}

###

POST {{Api_HostAddress}}/api/accounts/logout
Content-Type: application/json
{}

###

GET {{Api_HostAddress}}/api/accounts/user-info
Accept: application/json

###

POST {{Api_HostAddress}}/api/accounts/register
Content-Type: application/json
{
  "email": "quang3@abc.com",
  "DisplayName": "quang3",
  "password": "Pa$$w0rd"
}

###

GET {{Api_HostAddress}}/api/profiles/3a98981f-d923-4a8a-9f7f-2dac96a6839f
Accept: application/json

###

GET {{Api_HostAddress}}/api/profiles/3a98981f-d923-4a8a-9f7f-2dac96a6839f/photos
Accept: application/json

###

POST {{Api_HostAddress}}/api/profiles/add-photo
Content-Type: multipart/form-data; boundary=boundary-string

--boundary-string
Content-Disposition: form-data; name="file"; filename="unnamed.jpg"
Content-Type: image/jpeg

< O:/something/unnamed.jpg
--boundary-string--

###

PUT {{Api_HostAddress}}/api/profiles/3a98981f-d923-4a8a-9f7f-2dac96a6839f
Content-Type: application/json
{
  "DisplayName": "Bobify",
  "Bio": "This is Bob bio"
}
###

PUT {{Api_HostAddress}}/api/profiles/set-main/e218abdd-3386-48fe-8806-31c1a7445d95
Accept: application/json

###

DELETE {{Api_HostAddress}}/api/profiles/photos/e218abdd-3386-48fe-8806-31c1a7445d95
Accept: application/json

###