GET {{Api_HostAddress}}/api/activities
Accept: application/json

###

POST {{Api_HostAddress}}/api/activities
Content-Type: application/json
{
  "Title": "title 1",
  "Description": "description xxx",
  "Category": "category xxx",
  "City": "city xxx",
  "Venue": "venue xxx"
}

###

PUT {{Api_HostAddress}}/api/activities
Content-Type: application/json
{
  "Id": "fc924402-e63a-4ed4-9ae8-84ef847d351f",
  "Title": "title 111",
  "Description": "description xxx",
  "Category": "category xxx",
  "City": "city xxx",
  "Venue": "venue xxx"
}


### 

POST {{Api_HostAddress}}/api/login
Content-Type: application/json
{
  "email": "bob@test.com",
  "password": "Pa$$w0rd"
}

### Login and receving Cookie

POST {{Api_HostAddress}}/api/login?useCookies=true
Content-Type: application/json
{
  "email": "bob@test.com",
  "password": "Pa$$w0rd"
}

###

POST {{Api_HostAddress}}/api/accounts/logout
Content-Type: application/json
{

}

###

GET {{Api_HostAddress}}/api/accounts/user-info
Accept: application/json

###